nemo:
  local_size: 1
  d_feature: 128
  distance_thr: 6
  weight_noise: 4e-3
  num_noise: 5
  max_group: 512
  backbone: resnetext
  separate_bank: True




incremental:
  increment_epoch: 50
  subsequent_increment_epoch: 50
  exemplar_strategy: pose_aware
  n_tasks: 4
  num_replay: 1
  white_hole: 1
  run_tsne: False
  memory_budget: 240

train:
  pos_reg: 0.2
  kd_reg: 10.0
  spatial_reg: 3.0 # from podnet paper
  freeze_first_n_epochs: 0
  kappa_main: 14.3
  kappa_kd: 0.5
  kappa_pos: 1.0

inference:
  inf_epochs: 30
  inf_bs: 8
  inf_lr: 5e-2
  inf_adam_beta_0: 0.4
  inf_adam_beta_1: 0.6
  inf_adam_eps: 1e-8
  inf_adam_weight_decay: 0
